//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login.CDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marca
    {
        public int id_marcas { get; set; }
        public string marca1 { get; set; }
    }
}
