//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login.CDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int id_usuario { get; set; }
        public int id_empleado { get; set; }
        public string usuario1 { get; set; }
        public string contrasena { get; set; }
        public int id_rol { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Role Role { get; set; }
    }
}
